FROM ruby:2.5.1

RUN apt-get update && apt-get install -y \
    build-essential \
    nodejs \
    mysql-server -f

RUN gem install rails
RUN mkdir  -p /home/app
WORKDIR /home/app
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install
COPY . .

CMD ["rails","s", "-b","0.0.0.0"]