FROM ruby:2.5.1
#descarga ruby
RUN apt-get update && apt-get install -y \
    build-essential \
    nodejs \
    mysql-server -f
#descarga dependencias
RUN gem install rails
RUN mkdir  -p /home/app
#crea app
WORKDIR /home/app

CMD bash